import {
    isFunction,
    isObject,
    isArray,
    isString,
    isNumber,
    isBoolean,
    isEquals,
    appendThousandsSeparator,
    formatPercent,
    limitText,
    base64encode,
    arrayBufferToString,
    stringToArrayBuffer,
    getNameByKeyValue,
    copyObjectTo,
    copyArrayTo,
    arrangeArrayWithNewStartIndex,
} from './common.js'

import {
    getUtcOffsetMinutesByUtcOffset,
    getUtcOffsetByUtcOffsetMinutes,
    getTimezoneOffset,
    getTimezoneOffsetMinutes,
    getBrowserTimezoneOffsetMinutes,
    getLocalDatetimeFromUnixTime,
    getUnixTimeFromLocalDatetime,
    getActualUnixTimeForStore,
    getDummyUnixTimeForLocalUsage,
    getCurrentUnixTime,
    getCurrentDateTime,
    parseDateFromUnixTime,
    formatUnixTime,
    formatTime,
    getUnixTime,
    getYear,
    getMonth,
    getYearAndMonth,
    getDay,
    getDayOfWeekName,
    getHour,
    getMinute,
    getSecond,
    getUnixTimeBeforeUnixTime,
    getUnixTimeAfterUnixTime,
    getMinuteFirstUnixTime,
    getMinuteLastUnixTime,
    getTodayFirstUnixTime,
    getTodayLastUnixTime,
    getThisWeekFirstUnixTime,
    getThisWeekLastUnixTime,
    getThisMonthFirstUnixTime,
    getThisMonthLastUnixTime,
    getThisYearFirstUnixTime,
    getThisYearLastUnixTime,
    getDateTimeFormatType,
    getShiftedDateRange,
    getDateRangeByDateType,
    isDateRangeMatchFullYears,
    isDateRangeMatchFullMonths,
} from './datetime.js'

import {
    numericCurrencyToString,
    stringCurrencyToNumeric,
    getExchangedAmount,
} from './currency.js'

import {
    generateRandomString,
    parseUserAgent,
    parseDeviceInfo,
    makeButtonCopyToClipboard,
    changeClipboardObjectText,
} from './misc.js'

import {
    transactionTypeToCategoryType,
    categoryTypeToTransactionType,
    getTransactionPrimaryCategoryName,
    getTransactionSecondaryCategoryName,
    allVisibleTransactionCategories,
} from './category.js'

import {
    getAccountCategoryInfo,
    getCategorizedAccounts,
    getVisibleCategorizedAccounts,
    getAllFilteredAccountsBalance,
} from './account.js'

export default {
    // common.js
    isFunction,
    isObject,
    isArray,
    isString,
    isNumber,
    isBoolean,
    isEquals,
    appendThousandsSeparator,
    formatPercent,
    limitText,
    base64encode,
    arrayBufferToString,
    stringToArrayBuffer,
    getNameByKeyValue,
    copyObjectTo,
    copyArrayTo,
    arrangeArrayWithNewStartIndex,

    // datetime.js
    getUtcOffsetMinutesByUtcOffset,
    getUtcOffsetByUtcOffsetMinutes,
    getTimezoneOffset,
    getTimezoneOffsetMinutes,
    getBrowserTimezoneOffsetMinutes,
    getLocalDatetimeFromUnixTime,
    getUnixTimeFromLocalDatetime,
    getActualUnixTimeForStore,
    getDummyUnixTimeForLocalUsage,
    getCurrentUnixTime,
    getCurrentDateTime,
    parseDateFromUnixTime,
    formatUnixTime,
    formatTime,
    getUnixTime,
    getYear,
    getMonth,
    getYearAndMonth,
    getDay,
    getDayOfWeekName,
    getHour,
    getMinute,
    getSecond,
    getUnixTimeBeforeUnixTime,
    getUnixTimeAfterUnixTime,
    getMinuteFirstUnixTime,
    getMinuteLastUnixTime,
    getTodayFirstUnixTime,
    getTodayLastUnixTime,
    getThisWeekFirstUnixTime,
    getThisWeekLastUnixTime,
    getThisMonthFirstUnixTime,
    getThisMonthLastUnixTime,
    getThisYearFirstUnixTime,
    getThisYearLastUnixTime,
    getDateTimeFormatType,
    getShiftedDateRange,
    getDateRangeByDateType,
    isDateRangeMatchFullYears,
    isDateRangeMatchFullMonths,

    // currency.js
    numericCurrencyToString,
    stringCurrencyToNumeric,
    getExchangedAmount,

    // misc.js
    generateRandomString,
    parseUserAgent,
    parseDeviceInfo,
    makeButtonCopyToClipboard,
    changeClipboardObjectText,

    // category.js
    transactionTypeToCategoryType,
    categoryTypeToTransactionType,
    getTransactionPrimaryCategoryName,
    getTransactionSecondaryCategoryName,
    allVisibleTransactionCategories,

    // account.js
    getAccountCategoryInfo,
    getCategorizedAccounts,
    getVisibleCategorizedAccounts,
    getAllFilteredAccountsBalance,
};
