blank_issues_enabled: false
contact_links:
  - name: Usage Questions
    url: https://github.com/Paxtiny/oscar/discussions
    about: Questions about using oscar can be discussed in GitHub Discussions.
