// Generated by scripts/build-legal.py from legal/details.json. Do not edit by hand.
// People are asked to accept the Terms and Privacy Policy again whenever this version changes.
export const LEGAL_VERSION = '2026-10-09';
export const LEGAL_TERMS_URL = '/legal/terms.html';
export const LEGAL_PRIVACY_URL = '/legal/privacy.html';
