#!/usr/bin/env python3
"""Builds the Terms of Service and Privacy Policy pages from legal/*.template.html and legal/details.json.

    python3 scripts/build-legal.py                 build public/legal/terms.html, public/legal/privacy.html and src/ext/legalVersion.ts
    python3 scripts/build-legal.py --check         fail if the generated files are out of date with the templates and details
    python3 scripts/build-legal.py --check --strict    also fail while any value in details.json still starts with REPLACE

The deploy workflow runs the strict check, so the pages cannot go live with a placeholder in them.
Values that still start with REPLACE are shown highlighted in yellow on the pages so they cannot be missed when testing.
The wording is a generic starting point, not legal advice: have a lawyer read it for your country before you rely on it.
"""
import html
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
LEGAL = ROOT / "legal"
OUT = ROOT / "public" / "legal"
VERSION_FILE = ROOT / "src" / "ext" / "legalVersion.ts"

PAGES = {"terms": "Terms of Service", "privacy": "Privacy Policy"}
PLACEHOLDER = re.compile(r"\{\{(\w+)\}\}")
CONDITIONAL = re.compile(r"<!--IF paid-->(.*?)<!--ELSE-->(.*?)<!--END-->", re.S)


class BuildError(Exception):
    pass


def is_placeholder(value):
    return isinstance(value, str) and value.startswith("REPLACE")


def validate(details):
    version = details.get("version", "")
    if not re.fullmatch(r"[A-Za-z0-9._-]{1,32}", str(version)):
        raise BuildError("version must be 1 to 32 letters, digits, dots, dashes or underscores")
    if details.get("paid_plans") is True and is_placeholder(details.get("refund_policy", "REPLACE")):
        raise BuildError("paid_plans is true, so refund_policy must be filled in")


def render_template(template, details):
    """Fills {{key}} values (HTML-escaped) and keeps the paid or free wording that applies."""
    paid = details.get("paid_plans") is True
    text = CONDITIONAL.sub(lambda m: m.group(1) if paid else m.group(2), template)

    def value(match):
        key = match.group(1)
        if key not in details:
            raise BuildError("the template uses {{%s}} but details.json has no such key" % key)
        raw = details[key]
        escaped = html.escape(str(raw), quote=True)
        return '<mark class="todo">%s</mark>' % escaped if is_placeholder(raw) else escaped

    return PLACEHOLDER.sub(value, text)


def page(title, body, details, current):
    nav = " ".join(
        '<a href="/legal/%s.html"%s>%s</a>' % (slug, ' aria-current="page"' if slug == current else "", label)
        for slug, label in PAGES.items()
    )
    css = (LEGAL / "style.css").read_text()
    name = html.escape(str(details["service_name"]))
    return (
        '<!doctype html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n'
        '<meta name="viewport" content="width=device-width, initial-scale=1">\n'
        '<meta name="robots" content="noindex">\n'
        "<title>%s</title>\n<style>\n%s</style>\n</head>\n<body>\n<nav>%s <a href=\"/\">Back to the app</a></nav>\n%s\n</body>\n</html>\n"
        % (html.escape(title), css, nav, body)
    ).replace("{{service_name}}", name)


def build(details):
    validate(details)
    files = {}
    for slug, title in PAGES.items():
        body = render_template((LEGAL / ("%s.template.html" % slug)).read_text(), details)
        files[OUT / ("%s.html" % slug)] = page("%s - %s" % (title, html.unescape(re.sub("<[^>]+>", "", str(details["service_name"])))), body, details, slug)

    files[VERSION_FILE] = (
        "// Generated by scripts/build-legal.py from legal/details.json. Do not edit by hand.\n"
        "// People are asked to accept the Terms and Privacy Policy again whenever this version changes.\n"
        "export const LEGAL_VERSION = '%s';\n"
        "export const LEGAL_TERMS_URL = '/legal/terms.html';\n"
        "export const LEGAL_PRIVACY_URL = '/legal/privacy.html';\n" % details["version"]
    )
    return files


def main(argv):
    check = "--check" in argv
    strict = "--strict" in argv
    details = json.loads((LEGAL / "details.json").read_text())

    try:
        files = build(details)
    except BuildError as error:
        print("ERROR:", error)
        return 1

    todo = [k for k, v in details.items() if not k.startswith("_") and is_placeholder(v)]
    # a refund policy is only used once plans are paid, so it does not block the free launch
    if details.get("paid_plans") is not True:
        todo = [k for k in todo if k != "refund_policy"]

    if check:
        stale = [str(p.relative_to(ROOT)) for p, content in files.items() if not p.exists() or p.read_text() != content]
        if stale:
            print("OUT OF DATE (run python3 scripts/build-legal.py):", ", ".join(stale))
            return 1
    else:
        OUT.mkdir(parents=True, exist_ok=True)
        for path, content in files.items():
            path.write_text(content)
            print("wrote", path.relative_to(ROOT))

    if todo:
        print("%s: still to fill in legal/details.json: %s" % ("ERROR" if strict else "note", ", ".join(todo)))
        if strict:
            return 1
    elif check:
        print("legal pages are up to date and complete")

    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
